### ISSUE TITLE
How to add stop vectors for new languages?

### ISSUE THREAD

**Issue by loctimize-devi** [luismond/tm2tb#28]
Hi thank you for this cool tool! We are trying to extend it with more Spacy languages. Adding the new language models was not an issue. However, when running the extractor, there are no stop_vectors found. Any hint where we can download some or create our own?
Thank you!
```
Traceback (most recent call last):
  File "/Users/devi/PycharmProjects/tm2tb/de_it_test.py", line 42, in <module>
    terms = extractor.extract_terms(span_range=(1, 3), incl_pos=['ADJ', 'NOUN', 'PROPN', 'ADP'])       # Extract terms
  File "/Users/devi/PycharmProjects/tm2tb/tm2tb/term_extractor.py", line 114, in extract_terms
    stops_embeddings_avg = np.load(os.path.join(file_dir, '..', 'stops_vectors', str(self.emb_dims), f'{self.lang}.npy'))
  File "/Users/devi/PycharmProjects/tm2tb/venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/devi/PycharmProjects/tm2tb/tm2tb/../stops_vectors/768/it.npy'

Process finished with exit code 1
```

**Comment by luismond** [comment]
Hello, thank you for raising this issue. 

Here is a script to create a "stop vector"

```
from sentence_transformers import SentenceTransformer
import numpy as np

# Use sentence model
trf_model = SentenceTransformer('LaBSE')

# Define stop words
stop_words = ['you', 'it', 'of', 'and', 'for', 'what', 'we', 'this']

# Vectorize stop words
stop_vectors = trf_model.encode(stop_words)

# Get vectors' average
stop_vector_avg = np.average(stop_vectors, axis=0).reshape(1, -1)

# Save average vector ("stop word vector")
np.save('test.npy', stop_vector_avg)
```

**Comment by loctimize-devi** [comment]
Thank you! 
Will try this out!
